import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

// font color="#800000"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>R&P Plastics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h2>
            <strong>Home</strong>
          </h2>
          <p>
            Welcome to R&P Plastics, LLC! Visit the "About Us" page to learn
            more about our company. To find information on the products we
            offer, please visit the "Products" page. If you have questions, care
            to leave a message, or would like to receive a quote, please{' '}
            <strong>
              <a href="#" target="_self">
                Contact Us
              </a>
            </strong>
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <div align="center">
          <strong>
            Website Copyright &copy;2012,R&P Plastics, LLC. All Rights Reserved.
          </strong>
        </div>
      </footer>
    </div>
  );
}
